# Make sure to check the documentation at http://goreleaser.com
# ---------------------------
# General
# ---------------------------
version: 2

before:
  hooks:
    - |
      sh -c "if [ \"${SKIP_GORELEASER_TESTS}\" = \"true\" ]; then
        echo 'Skipping tests (SKIP_GORELEASER_TESTS=true)'
      else
        magex test
      fi"
changelog:
  use: github
  sort: asc
  abbrev: 0
  format: '[`{{ slice .SHA 0 7 }}`]({{ .GitURL }}/commit/{{ .SHA }}): {{ .Message }}{{ with .AuthorUsername }} (@{{ . }}){{ end }}'
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "Documentation"
      regexp: '^.*?docs?(\([[:word:]]+\))??!?:.+$'
      order: 300
    - title: "Refactoring"
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 400
    - title: "Other Changes"
      order: 9999
  filters:
    exclude:
      - "^test:"
      - "^Merge pull request"
      - "^Merge branch"

# ---------------------------
# Builder
# ---------------------------
builds:
  - id: sigil
    main: ./cmd/sigil
    binary: sigil
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildDate={{.Date}}

# ---------------------------
# Archives
# ---------------------------
archives:
  - id: sigil
    name_template: >-
      {{- .ProjectName }}_{{- .Version }}_{{- .Os }}_{{- .Arch }}
    files:
      - LICENSE
      - README.md

# ---------------------------
# Checksum
# ---------------------------
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

# ---------------------------
# Github Release
# ---------------------------
release:
  prerelease: "false"
  name_template: "Release v{{.Version}}"
  replace_existing_artifacts: true

# ---------------------------
# Announce
# ---------------------------
announce:
  # See more at: https://goreleaser.com/customization/announce/#slack
  slack:
    enabled: false
    message_template: "{{ .ProjectName }} {{ .Tag }} is out! Changelog: https://github.com/{{ .GitOwner }}/{{ .ProjectName }}/releases/tag/{{ .Tag }}"
    channel: "#test_slack"
    # username: ''
    # icon_emoji: ''
    # icon_url: ''

  # See more at: https://goreleaser.com/customization/announce/#twitter
  twitter:
    enabled: false
    message_template: "{{ .ProjectName }} {{ .Tag }} is out!"

  # See more at: https://goreleaser.com/customization/announce/#discord
  discord:
    enabled: false
    message_template: "{{ .ProjectName }} {{ .Tag }} is out!"
    # Defaults to `GoReleaser`
    author: ""
    # Defaults to `3888754` - the grey-ish from goreleaser
    color: ""
    # Defaults to `https://goreleaser.com/static/avatar.png`
    icon_url: ""

  # See more at: https://goreleaser.com/customization/announce/#reddit
  reddit:
    enabled: false
    # Application ID for Reddit Application
    application_id: ""
    # Username for your Reddit account
    username: ""
    # Defaults to `{{ .GitURL }}/releases/tag/{{ .Tag }}`
    # url_template: 'https://github.com/{{ .GitOwner }}/{{ .ProjectName }}/releases/tag/{{ .Tag }}'
    # Defaults to `{{ .ProjectName }} {{ .Tag }} is out!`
    title_template: "{{ .ProjectName }} {{ .Tag }} is out!"
