project:
  name: sigil
  binary: sigil
  module: github.com/mrz1836/sigil
  main: ./cmd/sigil/main.go

build:
  # Custom ldflags with version injection
  ldflags:
    - "-s -w"
    - "-X main.version={{.Version}}"
    - "-X main.commit={{.Commit}}"
    - "-X main.buildDate={{.Date}}"
  flags:
    - "-trimpath"
  output: "./cmd/sigil"

test:
  # Match CI timeout configuration (TEST_TIMEOUT_RACE_COVER in .github/env/)
  # Default magex timeout is 10m which was killing tests prematurely
  timeout: 30m
