# Temporary overrides for bulk operations implementation
# These functions have inherent complexity due to multi-phase algorithms

linters-settings:
  gocognit:
    min-complexity: 25  # Allow higher complexity for bulk operations
  nestif:
    min-complexity: 20  # Allow deeper nesting for bulk operations

issues:
  exclude-rules:
    # Bulk operations inherently complex
    - path: internal/chain/bsv/bulk\.go
      linters:
        - gocognit
        - funcorder
    # Discovery has complex scanning logic
    - path: internal/discovery/(scanner|recovery|parallel)\.go
      linters:
        - gocognit
        - nestif
        - funcorder
        - gosec  # G115 false positives on index conversions
    # UTXO store has complex validation
    - path: internal/utxostore/(validation|scan)\.go
      linters:
        - gocognit
        - gosec  # G115 false positives on uint64->int64
    # Sweep service has complex transaction building
    - path: internal/service/transaction/sweep\.go
      linters:
        - gocognit
        - nestif
    # CLI has complex user interaction flows
    - path: internal/cli/tx\.go
      linters:
        - gocognit
        - nestif
